apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "cave-roguelike.name" . }}
spec:
  hosts:
  - {{ include "cave-roguelike.name" . }}
  http:
  - route:
    - destination:
        host: {{ include "cave-roguelike.name" . }}
        # subset: v1