{{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: roguelike
  labels:
    roguelike
spec:
  lookupPolicy:
    local: true
{{- end }}