apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "entrance-roguelike.name" . }}
spec:
  host: {{ include "entrance-roguelike.name" . }}
  subsets:
  - name: v1
    labels:
      version: v1