apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monsters-roguelike.name" . }}
  labels:
    {{- include "monsters-roguelike.labels" . | nindent 4 }}
{{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") }}
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from":{
            "kind":"ImageStreamTag",
            "name":"{{ include "monsters-roguelike.imageName" . }}"
          },
          "fieldPath":"spec.template.spec.containers[0].image"
        }
      ]
{{- end }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "monsters-roguelike.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        {{- include "monsters-roguelike.labels" . | nindent 8 }}
    spec:
{{- if .Values.deploy.initContainers }}
      initContainers:
        {{- tpl (toYaml .Values.deploy.initContainers) . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.image.name }}
          image: {{ include "monsters-roguelike.imageName" . }}
          ports:
{{- range .Values.deploy.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
{{- end }}
{{- if .Values.deploy.resources }}
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
{{- end }}
{{- if .Values.deploy.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .Values.deploy.livenessProbe) . | nindent 12 }}
{{- end }}
{{- if .Values.deploy.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .Values.deploy.readinessProbe) . | nindent 12 }}
{{- end }}
{{- if .Values.deploy.env }}
          env:
            - name: server
              value: {{ .Values.server }}
            {{- tpl (toYaml .Values.deploy.env) . | nindent 12 }}
{{- end }}
{{- if .Values.deploy.envFrom }}
          envFrom:
            {{- tpl (toYaml .Values.deploy.envFrom) . | nindent 12 }}
{{- end }}
          volumeMounts:
{{- if .Values.deploy.volumeMounts }}
            {{- tpl (toYaml .Values.deploy.volumeMounts) . | nindent 12 }}
{{- end }}
{{- if .Values.deploy.extraContainers }}
        {{- tpl (toYaml .Values.deploy.extraContainers) . | nindent 8 }}
{{- end }}
      volumes:
        - name: default
          configMap:
            name: {{ include "monsters-roguelike.name" . }}
{{- if .Values.deploy.volumes }}
        {{- tpl (toYaml .Values.deploy.volumes) . | nindent 8 }}
{{- end }}